module arm(
	sys_clk,
	sys_rst_n,
	rdata,
	rx_sig,
	pwm1,
	pwm2,
	pwm3,
	pwm4,
	pwm5,
	pwm6);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input sys_rst_n;
	input [7:0] rdata;
	input rx_sig;
	output pwm1;
	output pwm2;
	output pwm3;
	output pwm4;
	output pwm5;
	output pwm6;

	wire sys_clk;
	wire sys_rst_n;
	wire [7:0] rdata;
	wire rx_sig;
	wire pwm1;
	wire pwm2;
	wire pwm3;
	wire pwm4;
	wire pwm5;
	wire pwm6;

	//----Code starts here: integrated by Robei-----
	
	wire rx_sig_negedge;
	wire [15:0] pwm_sel1;
	wire [15:0] pwm_sel2;
	wire [15:0] pwm_sel3;
	wire [15:0] pwm_sel4;
	wire [15:0] pwm_sel5;
	wire [15:0] pwm_sel6;
	
	
	reg [15:0] pwm_sel1_r;
	reg [15:0] pwm_sel2_r;
	reg [15:0] pwm_sel3_r;
	reg [15:0] pwm_sel4_r;
	reg [15:0] pwm_sel5_r;
	reg [15:0] pwm_sel6_r;
	
	
	reg rx_sig_dly;
	
	reg ok_10ms;
	reg [31:0] cnt_10ms;
	
	reg [3:0] lift_flag;
	
	
	
	
	parameter pwm1_min=500;
	parameter pwm1_max=2500;
	
	parameter pwm2_min=800;
	parameter pwm2_max=2000;
	
	parameter pwm3_min=500;
	parameter pwm3_max=2100;
	
	parameter pwm4_min=700;
	parameter pwm4_max=2300;
	
	parameter pwm5_min=500;
	parameter pwm5_max=2500;
	
	parameter pwm6_min=500;
	parameter pwm6_max=1500;
	
	assign pwm_sel1=pwm_sel1_r;
	assign pwm_sel2=pwm_sel2_r;
	assign pwm_sel3=pwm_sel3_r;
	assign pwm_sel4=pwm_sel4_r;
	assign pwm_sel5=pwm_sel5_r;
	assign pwm_sel6=pwm_sel6_r;
	
	
	
	assign rx_sig_negedge = ~rx_sig & rx_sig_dly; //下降沿
	
	always@(posedge sys_clk or negedge sys_rst_n) begin
	    if(!sys_rst_n)
	        rx_sig_dly <= 1'b0;
	    else
	        rx_sig_dly <= rx_sig;
	end
	
	always@(posedge sys_clk,negedge sys_rst_n)
	begin
	    if(!sys_rst_n)begin
	        cnt_10ms <= 1'b0;
	        ok_10ms <= 1'b0;
	    end
	    else begin
	            if(cnt_10ms ==150000)begin
	                cnt_10ms <= 1'b0;
	                ok_10ms <= 1'b1;
	            end
	            else begin
	                cnt_10ms <= cnt_10ms + 1'b1;
	                ok_10ms <= 1'b0;
	            end
	    end
	end
	
	always @(posedge sys_clk or negedge sys_rst_n)begin
	    if(!sys_rst_n)begin
	        pwm_sel1_r<=16'd1620;
	        pwm_sel2_r<=16'd1400;
	        pwm_sel3_r<=16'd1300;
	        pwm_sel4_r<=16'd1600;
	        pwm_sel5_r<=16'd1550;
	        pwm_sel6_r<=16'd1500;
	        lift_flag<=0;
	        end
	    else if(rx_sig_negedge)
	        case(rdata)
	            8'h00: begin
	                     pwm_sel1_r<=pwm_sel1_r>=pwm1_max?pwm1_max:pwm_sel1_r+16'd8;
	                   
	                   end
	            8'h01: begin
	                      pwm_sel1_r<=pwm_sel1_r<=pwm1_min?pwm1_min:pwm_sel1_r-16'd8;
	                     
	                   end
	                   ///////////////////////////////////////////////////////////////////
	            8'h02: begin
	                     pwm_sel2_r<=pwm_sel2_r<=pwm2_min?pwm2_min:pwm_sel2_r-16'd10;
	                   end
	            8'h03: begin
	              
	                      pwm_sel2_r<=pwm_sel2_r>=pwm2_max?pwm2_max:pwm_sel2_r+16'd10;
	                   end
	                   ///////////////////////////////////////////////////////////
	            8'h04: begin
	                     pwm_sel3_r<=pwm_sel3_r>=pwm3_max?pwm3_max:pwm_sel3_r+16'd10;
	                     
	                   end
	            8'h05: begin
	                      pwm_sel3_r<=pwm_sel3_r<=pwm3_min?pwm3_min:pwm_sel3_r-16'd10;
	                      
	                   end
	                   /////////////////////////////////////////////
	            8'h06: begin
	                     pwm_sel4_r<=pwm_sel4_r>=pwm4_max?pwm4_max:pwm_sel4_r+16'd10;
	                    
	                   end
	            8'h07: begin
	                      pwm_sel4_r<=pwm_sel4_r<=pwm4_min?pwm4_min:pwm_sel4_r-16'd10;
	                     
	                   end
	                   ////////////////////////////////////////////////////
	            8'h08: begin
	                     pwm_sel5_r<=pwm_sel5_r>=pwm5_max?pwm5_max:pwm_sel5_r+16'd10;
	                     
	                   end
	            8'h09: begin
	                      pwm_sel5_r<=pwm_sel5_r<=pwm5_min?pwm5_min:pwm_sel5_r-16'd10;
	                      
	                   end
	                   /////////////////////////////////////
	            8'h4a: begin
	                     pwm_sel6_r<=pwm_sel6_r>=pwm6_max?pwm6_max:pwm_sel6_r+16'd20;
	                     
	                     
	                   end
	            8'h4b: begin
	                      pwm_sel6_r<=pwm_sel6_r<=pwm6_min?pwm6_min:pwm_sel6_r-16'd20;
	                   
	                   end
	
	            8'h41: begin
	                     lift_flag<=1;
	                     
	                   end
	            8'h42: begin
	                      lift_flag<=2;
	                   end
	                   
	                   
	            8'h0c: begin///////////举起
	                        
	                        pwm_sel2_r<=16'd1400;
	                        pwm_sel3_r<=16'd1300;
	                        pwm_sel4_r<=16'd1600;
	                        pwm_sel5_r<=16'd1550;
	                   end
	            8'h0d: begin///////////放下
		                        
		                        pwm_sel2_r<=16'd1040;
		                        pwm_sel3_r<=16'd1520;
		                        pwm_sel4_r<=16'd1100;
		                        pwm_sel5_r<=16'd1550;
		                   end
		            8'h0e: begin///////////放下
		                        pwm_sel2_r<=16'd1040;
		                        pwm_sel3_r<=16'd1520;
		                        pwm_sel4_r<=16'd1100;
		                        pwm_sel5_r<=16'd1550;
		                    end
	            8'h0f: begin//////////往外
	                        pwm_sel2_r<=pwm_sel2_r<=pwm2_min?pwm2_min:pwm_sel2_r-16'd5;
	                        pwm_sel3_r<=pwm_sel3_r<=pwm3_min?pwm3_min:pwm_sel3_r-16'd8;
	                        pwm_sel4_r<=pwm_sel4_r>=pwm4_max?pwm4_max:pwm_sel4_r+16'd5;
	                    end
	            8'h10: begin///////////往内
	                        pwm_sel2_r<=pwm_sel2_r>=pwm2_max?pwm2_max:pwm_sel2_r+16'd5;
	                        pwm_sel3_r<=pwm_sel3_r>=pwm3_max?pwm3_max:pwm_sel3_r+16'd8;
	            
	                        pwm_sel4_r<=pwm_sel4_r<=pwm4_min?pwm4_min:pwm_sel4_r-16'd5;
	                    end
	            8'h11: begin////////////往下
	                        pwm_sel2_r<=pwm_sel2_r<=pwm2_min?pwm2_min:pwm_sel2_r-16'd2;                        
	                        pwm_sel3_r<=pwm_sel3_r>=pwm3_max?pwm3_max:pwm_sel3_r+16'd8;
	                        
	                        pwm_sel4_r<=pwm_sel4_r>=pwm4_max?pwm4_max:pwm_sel4_r+16'd10;
	                    end
	            8'h12: begin///////////往上
	                        
	                        
	                        pwm_sel2_r<=pwm_sel2_r>=pwm2_max?pwm2_max:pwm_sel2_r+16'd2;
	                        pwm_sel3_r<=pwm_sel3_r<=pwm3_min?pwm3_min:pwm_sel3_r-16'd8;
	                        pwm_sel4_r<=pwm_sel4_r<=pwm4_min?pwm4_min:pwm_sel4_r-16'd10;
	                    end
	            8'h15: begin///////////左边
	                        pwm_sel1_r<=16'd2300;
	                    end
	            8'h16: begin//////////右边
	                        pwm_sel1_r<=16'd1625;
	                    end
	            8'h17: begin//////////前面
	                        pwm_sel1_r<=16'd950;
	                    end
	            
	                   //////////////////////////////
	         default:  begin
	                        pwm_sel1_r<=pwm_sel1_r;
	                        pwm_sel2_r<=pwm_sel2_r;
	                        pwm_sel3_r<=pwm_sel3_r;
	                        pwm_sel4_r<=pwm_sel4_r;
	                        pwm_sel5_r<=pwm_sel5_r;
	                        pwm_sel6_r<=pwm_sel6_r;
	                   end
	        endcase
	     else if(lift_flag==1&&ok_10ms)begin
	            if(pwm_sel2_r<16'd1400)
	                pwm_sel2_r<= pwm_sel2_r+1;
	            else
	                pwm_sel2_r<= pwm_sel2_r-1;
	            if(pwm_sel3_r<16'd1300)
	                pwm_sel3_r<= pwm_sel3_r+1;
	            else
	                pwm_sel3_r<= pwm_sel3_r-1;
	            if(pwm_sel4_r<16'd1600)
	                pwm_sel4_r<= pwm_sel4_r+1;
	            else
	                pwm_sel4_r<= pwm_sel4_r-1;
	           
	            if(pwm_sel2_r==16'd1400&&pwm_sel3_r==16'd1300&&pwm_sel4_r==16'd1600) 
	                    lift_flag<=0; 
	        end
	    else if(lift_flag==2&&ok_10ms)begin
		            if(pwm_sel2_r<16'd1040)
		                pwm_sel2_r<= pwm_sel2_r+1;
		            else
		                pwm_sel2_r<= pwm_sel2_r-1;
		            if(pwm_sel3_r<16'd1520)
		                pwm_sel3_r<= pwm_sel3_r+1;
		            else
		                pwm_sel3_r<= pwm_sel3_r-1;
		            if(pwm_sel4_r<16'd1100)
		                pwm_sel4_r<= pwm_sel4_r+1;
		            else
		                pwm_sel4_r<= pwm_sel4_r-1;
		            if(pwm_sel2_r==16'd1040&&pwm_sel3_r==16'd1520&&pwm_sel4_r==16'd1100) 
		                    lift_flag<=0; 
		        end
	    else begin
	            pwm_sel1_r<=pwm_sel1_r;
	            pwm_sel2_r<=pwm_sel2_r;
	            pwm_sel3_r<=pwm_sel3_r;
	            pwm_sel4_r<=pwm_sel4_r;
	            pwm_sel5_r<=pwm_sel5_r;
	            pwm_sel6_r<=pwm_sel6_r;
	            
	        end
	           
	end
	
	
	//---Module instantiation---
	pwm_20ms pwm_20ms1(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel1),
		.pwm_out(pwm1));

	pwm_20ms pwm_20ms2(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel2),
		.pwm_out(pwm2));

	pwm_20ms pwm_20ms3(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel3),
		.pwm_out(pwm3));

	pwm_20ms pwm_20ms4(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel4),
		.pwm_out(pwm4));

	pwm_20ms pwm_20ms5(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel5),
		.pwm_out(pwm5));

	pwm_20ms pwm_20ms6(
		.sys_clk(sys_clk),
		.sys_rst_n(sys_rst_n),
		.pwm_sel(pwm_sel6),
		.pwm_out(pwm6));

endmodule    //arm

