module pwm_20ms(
	sys_clk,
	sys_rst_n,
	pwm_sel,
	pwm_out);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input sys_rst_n;
	input [15:0] pwm_sel;
	output pwm_out;

	wire sys_clk;
	wire sys_rst_n;
	wire [15:0] pwm_sel;
	reg pwm_out;

	//----Code starts here: integrated by Robei-----
	
	
	
	parameter CNT_20MS_MAX = 20'd666666;
	
	
	reg [19:0] cnt_20ms;
	reg [7:0] cnt_1s;
	
	
	wire [19:0]pwm_sel_r;
	
	
	assign pwm_sel_r=(pwm_sel*333)/10;
	
	always@(posedge sys_clk or negedge sys_rst_n) begin
	    if(!sys_rst_n)
	        cnt_20ms <= 7'b0;
	    else if(cnt_20ms == (CNT_20MS_MAX - 7'b1 ))
	        cnt_20ms <= 7'b0;
	    else
	        cnt_20ms <= cnt_20ms + 7'b1;
	end
	
	
	
	always@(posedge sys_clk or negedge sys_rst_n) begin
	    if(!sys_rst_n)
	        pwm_out <= 1'b0;
	    else if(cnt_20ms <= pwm_sel_r)
	        pwm_out <= 1'b1;
	    else
	        pwm_out <= 1'b0;
	end
endmodule    //pwm_20ms

